/* ═══════════════════════════════════════════════════════════════════════
   실제 부정수급 사례 DB — 공개 자료(정부 발표·감사·판결·언론 보도) 기반 106건
   src: 출처 약칭 | cat: 신고 구분 | amt: 금액(만원, 0=미공개) | conf: 확인단계
   risk: 부정 확률(공개 확인 정도 + 수법의 명백성) | logic: 대응 탐지 로직
   ═══════════════════════════════════════════════════════════════════════ */
const SRC = {
  moef:   {n:"기획재정부 국고보조금 부정징후 점검", u:"https://www.moef.go.kr/nw/nes/detailNesDtaView.do?searchBbsId1=MOSFBBS_000000000028&searchNttId1=MOSF_000000000073175"},
  gosims: {n:"e나라도움 보조금 부정 주요 사례", u:"https://www.gosims.go.kr/hg/hg002/retrieveIllegalcaseList.do"},
  bojo:   {n:"보조금통합포털 부정수급 제보·공개", u:"https://www.bojo.go.kr/ga/retrieveReport.do"},
  acrc:   {n:"국민권익위 공공재정 부정수급 집계", u:"https://www.acrc.go.kr/menu.es?mid=a10101070300"},
  clean:  {n:"청렴포털 부정청구 사례(어린이집편)", u:"https://www.clean.go.kr/board.es?act=view&bid=2003&list_no=30144158&mid=a10610000000"},
  mois:   {n:"행정안전부 지방보조금 일제점검", u:"https://www.mois.go.kr/frt/sub/a03/unfairClaim/screen.do"},
  seoul:  {n:"서울시 지방보조금 부정수급 사례", u:"https://news.seoul.go.kr/gov/subsidy-fraud-cases"},
  moel:   {n:"고용노동부 부정수급 적발 발표", u:"https://www.moel.go.kr/news/enews/report/enewsView.do?news_seq=17206"},
  molit:  {n:"국토교통부 유가보조금 합동점검", u:"http://www.molit.go.kr/USR/NEWS/m_71/dtl.jsp?id=155438219"},
  kaia:   {n:"국가 R&D 연구비 부적정집행 사례집", u:"https://www.kaia.re.kr/portal/cmm/fms/FileDown.do?atchFileId=FILE_000000000039106&fileSn=2"},
  bai:    {n:"감사원 전력기금·태양광 감사", u:"https://www.safetimes.co.kr/news/articleView.html?idxno=205849"},
  court:  {n:"법원 판결(공개 판례)", u:"https://www.law.go.kr/precInfoP.do?precSeq=185613"},
  nhis:   {n:"건보공단 부당청구 적발·포상", u:"https://www.g-enews.com/article/Real-Estate/2026/05/202605200947481769ea13369bfa_1"},
  mcst:   {n:"문화체육관광부 명단공표 공고", u:"https://www.mcst.go.kr/site/s_notice/notice/noticeView.jsp?pSeq=19113"},
  kosaf:  {n:"한국장학재단 근로장학금 점검", u:"https://www.eduinnews.co.kr/news/articleView.html?idxno=34831"},
  press:  {n:"언론 보도(정부 발표 인용)", u:"https://www.hankyung.com/article/2026080703927"},
};
/* cat 코드 → 신고 구분(관할·보상 체계) */
const CATS = {
  gukgo: {n:"국고보조금",     portal:"e나라도움 / 보조금통합포털",     law:"보조금법 §40·41, 공공재정환수법", rate:.30, cap:300000},
  local: {n:"지방보조금",     portal:"지자체 감사부서 / 청렴포털",       law:"지방보조금법, 공공재정환수법",   rate:.30, cap:300000},
  bokji: {n:"복지급여",       portal:"복지로 129 / 1398",              law:"국민기초생활보장법 §49, 공공재정환수법", rate:.30, cap:300000},
  goyong:{n:"고용·노동지원금", portal:"고용노동부 1350 / 고용보험",      law:"고용보험법 §116, 추가징수 최대 5배", rate:.30, cap:300000},
  uiryo: {n:"건강·요양급여",   portal:"건보공단 / 심평원 신고센터",       law:"국민건강보험법 §57, 노인장기요양보험법", rate:.30, cap:2000},
  rnd:   {n:"연구개발비(R&D)", portal:"범부처통합연구지원시스템 / e나라도움", law:"국가연구개발혁신법 §31·32",      rate:.30, cap:300000},
  nongsu:{n:"농림·수산 지원금", portal:"농관원 / 해수부 신고센터",         law:"농업농촌공익직불법 §15, 조세특례제한법", rate:.30, cap:300000},
  gita:  {n:"기타 공공재정",   portal:"청렴포털 / 국민신문고",            law:"공공재정환수법 §8",              rate:.30, cap:300000},
};
/* conf 코드 → 확인 단계(부정 확률 가중) */
const CONF = {court:"법원 확정판결", audit:"정부 감사·점검 적발", agency:"기관 환수·행정처분", stat:"정부 통계 유형"};

const CASES = [
/* ── 국고보조금 (기재부·e나라도움 발표 사례) ───────────────────────── */
{t:"친인척 대주주 업체에 5년간 용역 수의계약 몰아주기", cat:"gukgo", amt:391000, y:2024, conf:"audit", src:"moef",
 d:"보조사업자가 친인척이 대주주인 업체에 매년 8억 원 규모 용역을 수의계약으로 몰아주는 방식으로 5년간 국고보조금 39억1000만 원을 편취.", logic:["family","shell"], risk:97},
{t:"자녀 명의 페이퍼컴퍼니 설립 후 수의계약", cat:"gukgo", amt:0, y:2024, conf:"audit", src:"moef",
 d:"자녀 명의로 유령회사를 만들어 수의계약을 체결, 적발을 회피하며 국고보조금 편취.", logic:["shell","family"], risk:96},
{t:"보유 장비 라벨갈이 후 신규 구매로 허위 정산", cat:"gukgo", amt:0, y:2024, conf:"audit", src:"moef",
 d:"원래 보유하던 장비에 라벨을 덧붙여 신규 구매한 것처럼 허위 계약서를 작성해 보조금 횡령.", logic:["label","forge"], risk:96},
{t:"쪼개기 계약·유령회사 허위계약 (전체 적발액의 87.4%)", cat:"gukgo", amt:3920000, y:2024, conf:"audit", src:"moef",
 d:"2023.7~2024.6 집행분 점검에서 거래계약 과정 부정이 392억 원으로 전체 적발액의 87.4%를 차지.", logic:["shell","inflate"], risk:95},
{t:"2024년 국고보조금 부정수급 630건·493억 적발", cat:"gukgo", amt:4930000, y:2024, conf:"audit", src:"moef",
 d:"부정 의심 보조사업 8,079건 점검 결과 630건·493억 원 적발. 건수 기준 역대 최대(전년 493건의 1.3배).", logic:["shell","family","inflate"], risk:94},
{t:"2025년 국고보조금 부정수급 992건·667.7억 적발", cat:"gukgo", amt:6677000, y:2025, conf:"audit", src:"moef",
 d:"2024년 하반기 집행분 대상 의심사례 1만780건 추출, 992건·667억7000만 원을 부정수급으로 적발(역대 최다).", logic:["shell","family","misuse"], risk:94},
{t:"2023년 국고보조금 493건·699.8억 적발", cat:"gukgo", amt:6998000, y:2023, conf:"audit", src:"moef",
 d:"부정징후 의심사업 7,521건 점검 결과 493건·699억8000만 원 적발.", logic:["shell","inflate"], risk:93},
{t:"특정 거래관리 부정(수의계약 조건 위반·계약 쪼개기)", cat:"gukgo", amt:0, y:2023, conf:"stat", src:"moef",
 d:"2023년 부정 유형 중 38.5%로 최다. 수의계약 조건 위반, 계약 쪼개기, 특정 업체 몰아주기.", logic:["shell","family"], risk:88},
{t:"급여성 경비 허위 지급·휴직 인력 인건비 청구", cat:"gukgo", amt:0, y:2023, conf:"stat", src:"moef",
 d:"2023년 부정 유형의 22.7%. 근무하지 않는 인력·휴직자에게 인건비를 지급한 것으로 처리.", logic:["ghost","payback"], risk:90},
{t:"가족 간 거래 (SFDS 탐지 패턴)", cat:"gukgo", amt:0, y:2023, conf:"stat", src:"moef",
 d:"2023년 부정 유형의 17.2%. 보조사업자와 가족 관계인 업체 간 거래를 SFDS가 자동 탐지.", logic:["family"], risk:87},
{t:"지출 증빙 미비 — 견적서 1장으로 자기 계좌 이체", cat:"gukgo", amt:0, y:2023, conf:"stat", src:"moef",
 d:"2023년 부정 유형의 12.2%. 견적서 1장만으로 집행액과 불일치하는 금액을 자기 계좌로 이체.", logic:["misuse","forge"], risk:89},
{t:"실제 근무 없는 직원 허위 등록 후 인건비 수령", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"gosims",
 d:"실제로 근무하지 않는 직원을 허위 등록해 인건비를 지급받은 전형적 유형.", logic:["ghost"], risk:93},
{t:"물품 단가·수량 부풀려 허위 매출전표 발행", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"gosims",
 d:"사업 운영자가 물품 단가와 수량을 부풀려 허위 매출전표를 발행하고 차액 편취.", logic:["inflate","forge"], risk:92},
{t:"외주업체 허위계약 후 용역대금 일부 환수(리베이트)", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"gosims",
 d:"외주업체와 허위계약을 맺고 지급한 용역대금 중 일부를 되돌려 받는 수법.", logic:["rebate","shell"], risk:93},
{t:"R&D 보조금으로 회사 채무 상환·차량 구입", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"gosims",
 d:"보조금으로 수령한 연구개발비를 회사 채무 상환, 차량 구입 등 개인·사업 무관 용도로 사용.", logic:["misuse"], risk:92},
{t:"근로사실 없는 근로자 인건비 지급 후 일부 회수", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"seoul",
 d:"국고보조금을 근로사실 없는 근로자 인건비로 지급한 뒤 일부를 돌려받아 유용.", logic:["ghost","payback"], risk:93},
{t:"거래업체에 앱 개발비·성과자료 제작비 과다 지급", cat:"gukgo", amt:0, y:2024, conf:"agency", src:"seoul",
 d:"단체 거래업체에 앱 개발비, 사업 성과자료 제작 등 명목으로 과다 지급 후 유용.", logic:["inflate","rebate"], risk:87},
{t:"세금계산서 발행 후 취소, 대금 미환입", cat:"gukgo", amt:0, y:2024, conf:"audit", src:"moef",
 d:"정산 증빙으로 제출한 세금계산서를 사후 취소하고 대금을 반환하지 않는 SFDS 탐지 패턴.", logic:["taxcxl"], risk:90},
{t:"출국자·사망자 명의 보조금 수급 (SFDS 패턴)", cat:"gukgo", amt:0, y:2024, conf:"audit", src:"moef",
 d:"해외 출국 중이거나 사망한 사람 명의로 집행된 지급 건을 SFDS가 탐지.", logic:["dead"], risk:95},
{t:"나라장터 입찰·상위 보조사업자 승인 없이 수의계약", cat:"gukgo", amt:0, y:2026, conf:"agency", src:"gosims",
 d:"나라장터 입찰과 상위 보조사업자 승인 절차를 거치지 않고 수의계약을 진행해 부정수급 결정.", logic:["shell","family"], risk:82},

/* ── 지방보조금 (행안부 일제점검·지자체) ─────────────────────────── */
{t:"2026 상반기 지방보조금 605건·147.2억 부정수급 적발", cat:"local", amt:1471600, y:2026, conf:"audit", src:"mois",
 d:"행안부가 2026.4.20~6.20 일제점검으로 605건, 147억1600만 원의 부정수급을 적발.", logic:["misuse","inflate"], risk:94},
{t:"쪼개기 계약 등 지방계약법 위반 (적발액 43.8%)", cat:"local", amt:644364, y:2026, conf:"audit", src:"mois",
 d:"행사운영비를 통합 발주하지 않고 운영비·시설비로 나눠 수의계약, 셔틀버스 임차 견적 부풀리기 등 92건 64억4364만 원.", logic:["shell","inflate"], risk:90},
{t:"지급 근거 부족 부정수급 205건", cat:"local", amt:273547, y:2026, conf:"audit", src:"mois",
 d:"적발 유형 중 최다(33.9%). 근거 없이 집행된 205건, 27억3547만 원.", logic:["misuse"], risk:84},
{t:"주민지원협의체, 1000만원 운동기구를 1300만원으로 허위 정산", cat:"local", amt:300, y:2026, conf:"audit", src:"mois",
 d:"실제 가격 1000만 원인 운동기구를 1300만 원에 구입한 것처럼 서류를 허위 작성해 정산.", logic:["inflate","forge"], risk:95},
{t:"문화재단, 직원 인건비 1000만원 중복 집행", cat:"local", amt:1000, y:2026, conf:"audit", src:"mois",
 d:"직원 인건비를 지방보조금과 영화제 입장권 수익금에서 각각 지급해 동일 인건비를 중복 집행.", logic:["double"], risk:91},
{t:"사업계획에 없는 배우자 인건비 지급", cat:"local", amt:0, y:2026, conf:"audit", src:"press",
 d:"사업계획에 없는 배우자에게 인건비를 지급하고, 기준을 초과한 식비·수당을 집행.", logic:["family","ghost"], risk:90},
{t:"보조금으로 개인 차량 주유비 집행", cat:"local", amt:0, y:2026, conf:"audit", src:"press",
 d:"지방보조금을 사업과 무관한 개인 차량 주유비로 사용.", logic:["misuse"], risk:91},
{t:"축제 주관단체, 주말 회식·개인 택시비·골프장 이용료 지출", cat:"local", amt:1459, y:2026, conf:"audit", src:"press",
 d:"업무추진비 65건 1459만 원을 주말 회식이나 사업장과 무관한 지역에서 사용.", logic:["misuse"], risk:92},
{t:"경북 지방보조금 605건·147억 의심사례", cat:"local", amt:1471600, y:2026, conf:"audit", src:"mois",
 d:"지자체 대상 점검에서 확인된 부정수급 의심 사례 집계.", logic:["misuse","inflate"], risk:86},
{t:"부여군체육회 보조금 횡령 — 지인 통장 동원, 15명 검찰 송치", cat:"local", amt:240000, y:2026, conf:"agency", src:"press",
 d:"체육회 보조금 24억 원 정산 보류. 지인 통장까지 동원한 횡령 의혹으로 경찰이 15명을 검찰 송치.", logic:["misuse","forge"], risk:93},
{t:"제주체육회 직원, 보조금·퇴직금·4대보험금 가족계좌 이체 횡령", cat:"local", amt:4600, y:2026, conf:"agency", src:"press",
 d:"보조금과 직원 퇴직금, 4대 보험금을 인출해 가족 계좌로 넘기는 방식으로 4600만 원 횡령.", logic:["misuse","family"], risk:96},
{t:"부산 민간단체 보조금, 회식·택시·골프장 유용", cat:"local", amt:0, y:2026, conf:"audit", src:"press",
 d:"문화예술 등 민간단체 보조금이 회식비·택시비·골프장 이용료로 유용된 사실 적발.", logic:["misuse"], risk:88},
{t:"자격 위조로 지방보조금 신청", cat:"local", amt:0, y:2025, conf:"stat", src:"seoul",
 d:"신청 자격이 없음에도 자격을 위조해 지방보조금을 신청·수령.", logic:["eligib","forge"], risk:89},
{t:"허위 견적서·세금계산서로 공사비 부풀리기", cat:"local", amt:0, y:2025, conf:"stat", src:"seoul",
 d:"정산서류를 조작해 공사비 등을 부풀려 보조금 횡령·편취.", logic:["inflate","forge"], risk:91},
{t:"보조금 취득재산 무단 매매·담보 제공", cat:"local", amt:0, y:2025, conf:"stat", src:"seoul",
 d:"보조금으로 취득한 재산을 지자체장 승인 없이 매매·양도·대여·담보 제공.", logic:["misuse"], risk:82},

/* ── 복지급여 ─────────────────────────────────────────────────── */
{t:"기초생활 부정수급 5년간 10.8만명·910억 환수 결정", cat:"bokji", amt:9100000, y:2025, conf:"agency", src:"press",
 d:"최근 5년간 10만8357명이 부정수급자로 적발, 환수 결정액 910억 원(이 중 346억 미환수).", logic:["eligib"], risk:92},
{t:"소득·재산 증가 미신고 (2024년 환수 최다 유형)", cat:"bokji", amt:2353200, y:2024, conf:"agency", src:"press",
 d:"2024년 기초생활 부정수급 환수 결정액 중 235억3200만 원으로 최대 비중.", logic:["eligib"], risk:88},
{t:"금융자산·부동산 취득 미신고 후 계속 수급", cat:"bokji", amt:0, y:2025, conf:"agency", src:"press",
 d:"금융자산과 부동산을 취득했음에도 신고하지 않고 기초생활급여를 계속 수급.", logic:["eligib"], risk:90},
{t:"타인 명의 차량 보유·사용하며 수급자격 유지", cat:"bokji", amt:0, y:2025, conf:"agency", src:"press",
 d:"차량을 타인 명의로 숨겨 보유·사용하면서 기초생활수급 자격을 유지.", logic:["eligib","forge"], risk:91},
{t:"위장이혼·사실혼 은닉으로 수급자격 유지", cat:"bokji", amt:0, y:2025, conf:"agency", src:"press",
 d:"위장 이혼하거나 사실혼 관계를 숨겨 부양의무자 기준을 회피하고 급여 수급.", logic:["eligib","forge"], risk:93},
{t:"혼인·사실혼 숨기고 한부모가족지원금 수급", cat:"bokji", amt:0, y:2026, conf:"audit", src:"acrc",
 d:"권익위 공공재정 부정수급 점검에서 확인된 대표 유형. 혼인·사실혼 관계를 숨기고 한부모 지원금 수급.", logic:["eligib","forge"], risk:92},
{t:"어린이집 출석부 허위 작성 (전체 부정의 16.6%)", cat:"bokji", amt:0, y:2025, conf:"audit", src:"clean",
 d:"원아·교육생 출석부를 허위 작성해 보조금 부정수급한 사례가 237건(16.6%)으로 집계.", logic:["pad","forge"], risk:91},
{t:"어린이집 보육교사 2명 허위 등록", cat:"bokji", amt:300, y:2025, conf:"agency", src:"clean",
 d:"충북 소재 어린이집이 보육교사 2명을 허위 등록해 약 300만 원 수령.", logic:["ghost"], risk:94},
{t:"어린이집 원장, 개인차량 주유비를 원 차량 유류비로 처리", cat:"bokji", amt:1200, y:2025, conf:"agency", src:"clean",
 d:"경북 민간어린이집 원장이 개인차량에 매월 100여만 원 주유하고 어린이집 차량 사용으로 속여 약 1200만 원을 사적 사용.", logic:["misuse","forge"], risk:95},
{t:"연구원·보육교사 등 직원 허위 등록 (15.3%)", cat:"bokji", amt:0, y:2025, conf:"stat", src:"clean",
 d:"직원 허위 등록 유형이 218건(15.3%)으로 두 번째로 많은 부정 유형.", logic:["ghost"], risk:90},
{t:"강남구 어린이집, 보조금 493만원 반환명령", cat:"bokji", amt:493, y:2025, conf:"agency", src:"clean",
 d:"어린이집 대표자에 대해 시정명령 처분 및 비용·보조금 493만2000원 반환명령 처분.", logic:["forge","pad"], risk:90},
{t:"어린이집 출석부 조작 보육료 부정수급 — 법원 반환 확정", cat:"bokji", amt:0, y:2025, conf:"court", src:"court",
 d:"출석부를 조작해 보육료를 부정수급한 사건에서 법원이 보조금 반환 의무를 인정.", logic:["pad","forge"], risk:97},
{t:"유령교사 내세운 어린이집 보조금 편취 — 실형", cat:"bokji", amt:0, y:2025, conf:"court", src:"court",
 d:"실재하지 않는 교사를 등록해 보조금을 받은 사건에서 법원이 유죄 판결.", logic:["ghost","forge"], risk:97},
{t:"이천시 장애인 거주시설 전 시설장, 보조금·후원금 8053만원 부당 사용", cat:"bokji", amt:8053, y:2021, conf:"agency", src:"press",
 d:"법인대표와 공모해 다양한 수법으로 보조금과 후원금 8053만 원을 부당 사용.", logic:["misuse","forge"], risk:95},
{t:"생활재활교사 채용 후 일반 행정업무 시키고 보조금 1891만원 횡령", cat:"bokji", amt:1891, y:2021, conf:"agency", src:"press",
 d:"공개채용 절차 없이 채용한 교사에게 재활과 무관한 행정업무를 시키고 재활업무를 한 것처럼 속여 횡령.", logic:["ghost","forge"], risk:94},
{t:"경기도 노인·장애인 복지시설 2곳 6명 검찰 송치", cat:"bokji", amt:0, y:2021, conf:"agency", src:"press",
 d:"경기도 공정특별사법경찰단 기획수사로 운영법인·시설장·법인대표 등 6명을 사회복지법 위반으로 송치.", logic:["misuse"], risk:92},
{t:"결식아동 급식비를 자녀 교육비로 전용", cat:"bokji", amt:0, y:2021, conf:"agency", src:"press",
 d:"복지법인이 결식아동 급식비 등 보조금을 자녀 교육비로 전용한 사실이 무더기 적발.", logic:["misuse"], risk:94},
{t:"권익위 정부보조금 부정수급 580억 환수", cat:"bokji", amt:5800000, y:2025, conf:"agency", src:"acrc",
 d:"국민권익위가 복지·보조금 부정수급 조사로 580억 원을 환수 조치.", logic:["eligib","ghost"], risk:88},

/* ── 고용·노동지원금 ─────────────────────────────────────────── */
{t:"사업주 공모 허위 육아휴직 — 82명 적발", cat:"goyong", amt:0, y:2024, conf:"agency", src:"moel",
 d:"사업주와 공모해 계속 근무하면서 육아휴직한 것처럼 사업주확인서를 제출해 급여를 받은 82명 적발.", logic:["ghost","forge"], risk:96},
{t:"모친 대표 회사서 근무하며 육아휴직급여 1100만원 수령", cat:"goyong", amt:1100, y:2023, conf:"agency", src:"moel",
 d:"모친이 대표인 회사에서 근무를 계속하면서 육아휴직급여 약 1100만 원을 부정수급.", logic:["family","ghost","forge"], risk:97},
{t:"육아휴직급여 부정수급 48.8억 (2024년 1~8월)", cat:"goyong", amt:488000, y:2024, conf:"agency", src:"moel",
 d:"8개월간 적발액 48억8000만 원으로 전년 연간(26억6900만 원) 대비 82.8% 급증.", logic:["ghost","forge"], risk:90},
{t:"친인척 사업장 허위 고용보험 취득 후 급여 수급", cat:"goyong", amt:0, y:2024, conf:"audit", src:"moel",
 d:"친인척 사업장에서 근무한 것처럼 고용보험 피보험자격을 허위 신고하고 육아휴직급여·실업급여 수급.", logic:["family","ghost","forge"], risk:94},
{t:"자진퇴사를 권고사직으로 위장해 실업급여 수급", cat:"goyong", amt:0, y:2025, conf:"stat", src:"moel",
 d:"자진퇴사임에도 권고사직·계약만료로 이직했다고 허위 신고해 실업급여 수급요건을 충족시킨 위장 퇴사.", logic:["eligib","forge"], risk:92},
{t:"허위 구직활동·면접확인서 제출로 실업인정", cat:"goyong", amt:0, y:2025, conf:"stat", src:"moel",
 d:"실제 하지 않은 입사지원을 한 것처럼 꾸미거나 아는 사업장에서 면접확인서를 허위로 받아 제출.", logic:["forge","pad"], risk:89},
{t:"실업급여 수급 중 취업·소득 미신고", cat:"goyong", amt:0, y:2025, conf:"stat", src:"moel",
 d:"수급 기간 중 국세청 소득 신고나 4대보험 취득 이력이 생겨 자동으로 불일치가 감지되는 유형.", logic:["eligib"], risk:93},
{t:"허위 고용으로 실업급여 편취 — 부산지법 유죄", cat:"goyong", amt:0, y:2024, conf:"court", src:"court",
 d:"실제 고용 사실 없이 피보험자격을 허위 취득시켜 실업급여를 받은 사건에서 유죄 판결(2024고정629).", logic:["ghost","forge"], risk:97},
{t:"고용노동부 부정수급자 218명·23.7억 적발", cat:"goyong", amt:237000, y:2024, conf:"agency", src:"moel",
 d:"고용노동부 기획조사로 부정수급자 218명, 23억7000만 원을 적발.", logic:["ghost","forge"], risk:91},
{t:"휴업 중인 근로자 출근 근로시키며 고용유지지원금 수령", cat:"goyong", amt:0, y:2024, conf:"agency", src:"moel",
 d:"고용유지조치 기간 중 휴업 중인 근로자가 사무실에 출근해 근로하면서 지원금을 부정수급.", logic:["ghost","forge"], risk:95},
{t:"휴업 사실 없이 출퇴근 기록 조작해 고용유지지원금 신청", cat:"goyong", amt:0, y:2024, conf:"agency", src:"moel",
 d:"휴업·휴직을 한 적이 없음에도 직원 출퇴근 기록을 조작해 지원금을 신청.", logic:["forge","pad"], risk:94},
{t:"출퇴근부·훈련실시 현황 허위 작성해 고용안정장려금 수령", cat:"goyong", amt:0, y:2026, conf:"audit", src:"acrc",
 d:"권익위 점검에서 확인된 유형. 출·퇴근부와 훈련실시 현황을 허위로 작성해 장려금 수령.", logic:["forge","pad"], risk:92},
{t:"청년디지털일자리 부정수급 83건·77개 기업 적발", cat:"goyong", amt:54000, y:2021, conf:"audit", src:"moel",
 d:"2991개 수혜기업 점검에서 77개 기업 83건 적발, 확인된 16건에 5억4000여만 원 반환명령.", logic:["ghost","family","payback"], risk:92},
{t:"청년일자리 지원금 — 허위 근로 6건", cat:"goyong", amt:0, y:2021, conf:"audit", src:"moel",
 d:"청년디지털일자리 부정수급 유형 중 허위 근로가 6건으로 최다.", logic:["ghost"], risk:93},
{t:"청년일자리 지원금 — 친·인척 채용 3건", cat:"goyong", amt:0, y:2021, conf:"audit", src:"moel",
 d:"친·인척을 형식적으로 채용해 지원금을 받은 사례 3건.", logic:["family","ghost"], risk:88},
{t:"청년일자리 지원금 — 임금 페이백 2건", cat:"goyong", amt:0, y:2021, conf:"audit", src:"moel",
 d:"지급한 임금 일부를 되돌려 받는 페이백 방식 2건 적발.", logic:["payback"], risk:94},
{t:"사회적기업 일자리창출사업 1억85만원 부정수급 — 형사고발", cat:"goyong", amt:10086, y:2024, conf:"agency", src:"press",
 d:"사회적기업이 1억85만5590원의 부정수급으로 반환처분 및 형사고발.", logic:["ghost","forge"], risk:95},
{t:"서울 사회적기업, 근로자 허위 등록 인건비 3047만원 수급 — 인증취소", cat:"goyong", amt:3047, y:2024, conf:"agency", src:"press",
 d:"근로자를 허위 등록해 인건비 3047만7000원을 부정수급, 인증 취소 처분.", logic:["ghost"], risk:94},
{t:"예비사회적기업 일자리 임금 1900만원 부정수급", cat:"goyong", amt:1900, y:2024, conf:"agency", src:"press",
 d:"지정 후 일자리 근로자 임금 지원 과정에서 1900만 원 부정수급 확인, 환수 진행.", logic:["ghost"], risk:91},
{t:"사회적기업 인증취소 127곳 (부정수급 급증)", cat:"goyong", amt:0, y:2024, conf:"stat", src:"press",
 d:"사회적기업 3737곳 중 127곳 인증 취소. 정부 지원 축소 후 부정수급 급증.", logic:["ghost"], risk:80},
{t:"바리스타학원 부정출결 — 6개월 정지·훈련기관 승인취소", cat:"goyong", amt:0, y:2025, conf:"agency", src:"press",
 d:"성남시 소재 학원이 훈련생 부정출결로 6개월 정지 및 훈련기관 승인 취소 처분.", logic:["pad","forge"], risk:90},
{t:"프로그래밍학원 대리출석 적발", cat:"goyong", amt:0, y:2025, conf:"agency", src:"press",
 d:"서울 강남구 학원에서 훈련생들이 식사 후 대리 출석한 사례 적발.", logic:["pad","forge"], risk:87},
{t:"훈련기관 아이디 임의 생성·허위 수료증으로 4770만원 수령", cat:"goyong", amt:4770, y:2024, conf:"court", src:"court",
 d:"훈련기관이 직원 아이디·패스워드를 임의 생성해 훈련을 조작하고 허위 수료증을 발급, 4769만8000원의 지원금 수령.", logic:["forge","pad","ghost"], risk:96},
{t:"산재보험 부정수급 징수결정 870억 중 521억 미환수", cat:"goyong", amt:8702600, y:2019, conf:"agency", src:"press",
 d:"근로복지공단이 2015~2019.7 반환명령한 산재 부당이득 870억2600만 원 중 521억500만 원 미환수.", logic:["forge","eligib"], risk:88},
{t:"망치로 자해 후 산재 요양급여 신청 — 실형", cat:"goyong", amt:0, y:2024, conf:"court", src:"court",
 d:"산재보험금을 노리고 고의로 손가락을 자해한 뒤 공사현장 재해로 위장해 요양급여 신청, 실형 선고.", logic:["forge","eligib"], risk:98},
{t:"산재·보험금 중복청구 의심자 61명 적발", cat:"goyong", amt:0, y:2024, conf:"agency", src:"press",
 d:"금융감독원이 동일 사고로 이중·허위 청구한 혐의자 61명을 적발.", logic:["double","forge"], risk:90},
{t:"건축주가 이웃 근로자 산재보상금 부정수급에 가담", cat:"goyong", amt:0, y:2024, conf:"court", src:"court",
 d:"건축주가 이웃 근로자의 산재보상금 부정수급에 가담한 사건에서 책임 인정 판결.", logic:["forge","eligib"], risk:94},

/* ── 건강·요양급여 ────────────────────────────────────────────── */
{t:"요양병원 사무장병원 요양급여 174억 환수처분", cat:"uiryo", amt:1740000, y:2018, conf:"court", src:"court",
 d:"의료인이 아닌 개인·법인이 요양병원을 개설·운영해 요양급여비 약 174억 원을 부당 수급, 건보공단 환수 처분.", logic:["eligib","shell"], risk:97},
{t:"금산군 사무장병원 136.5억 편취 — 징역 3년 확정", cat:"uiryo", amt:1365022, y:2020, conf:"court", src:"court",
 d:"의료인이 아닌 자가 의료법인 명의 요양병원을 실질 운영하며 요양급여 136억5022만 원 편취, 징역 3년 확정.", logic:["eligib","shell","forge"], risk:98},
{t:"요양보호사, 신발장 문짝 떼어 태그 조작 — 3740만원 환수", cat:"uiryo", amt:3740, y:2026, conf:"court", src:"court",
 d:"출퇴근 태그가 부착된 신발장 문짝을 차량에 싣고 다니며 서비스 제공 기록을 조작, 3740만5240원 환수처분 적법 판결.", logic:["forge","pad"], risk:98},
{t:"방문요양 서비스 시간 부풀려 급여비 청구", cat:"uiryo", amt:0, y:2026, conf:"court", src:"court",
 d:"2021.3~2023.2 수급자 부부에게 제공한 방문요양 시간을 부풀려 전산 입력 후 급여비 청구.", logic:["pad","forge"], risk:95},
{t:"장기요양기관 부당청구 2024년 1786건·464.2억", cat:"uiryo", amt:4641600, y:2024, conf:"agency", src:"nhis",
 d:"장기요양기관 부당청구 적발 1786건, 464억1600만 원.", logic:["pad","ghost"], risk:90},
{t:"장기요양기관 부당청구 2023년 2085건·666.8억", cat:"uiryo", amt:6667600, y:2023, conf:"agency", src:"nhis",
 d:"장기요양기관 부당청구 적발 2085건, 666억7600만 원(최근 3년 중 최대).", logic:["pad","ghost"], risk:90},
{t:"장기요양기관 부당청구 2022년 1668건·523.7억", cat:"uiryo", amt:5236700, y:2022, conf:"agency", src:"nhis",
 d:"장기요양기관 부당청구 적발 1668건, 523억6700만 원.", logic:["pad","ghost"], risk:89},
{t:"요양보호사 미출근인데 근무 기록 — 서비스 미제공 청구", cat:"uiryo", amt:0, y:2025, conf:"stat", src:"nhis",
 d:"가장 흔한 유형. 요양보호사가 출근하지 않았는데 근무한 것처럼 기록하고 급여비 청구.", logic:["ghost","forge"], risk:93},
{t:"이용자 병원 입원 중인데 재가서비스 급여 청구", cat:"uiryo", amt:0, y:2025, conf:"stat", src:"nhis",
 d:"수급자가 병원에 입원 중임에도 재가서비스를 제공한 것처럼 급여를 청구.", logic:["dead","forge"], risk:94},
{t:"30분 서비스를 1시간으로 청구 (시간 부풀리기)", cat:"uiryo", amt:0, y:2025, conf:"stat", src:"nhis",
 d:"1시간 서비스를 30분만 제공하고 1시간으로 청구하거나 등급별 한도를 초과 청구.", logic:["pad"], risk:88},
{t:"요양기관 11곳 부당청구 3.5억 — 포상금 5900만원 지급", cat:"uiryo", amt:35000, y:2026, conf:"agency", src:"nhis",
 d:"건강보험 신고 포상심의위원회 심의로 부당청구 3억5000만 원 확인, 신고자에게 포상금 5900만 원 지급.", logic:["pad","forge"], risk:93},
{t:"사무장병원 실소유주 환수액이 명의 대여 법인보다 클 수 있다 — 대법", cat:"uiryo", amt:0, y:2026, conf:"court", src:"court",
 d:"대법원이 사무장병원 부당급여 환수에서 명의자보다 실운영자에게 더 많이 부과할 수 있다고 판시.", logic:["shell","eligib"], risk:96},

/* ── 연구개발비(R&D) ──────────────────────────────────────────── */
{t:"국가 R&D 부당집행 267건·23.7억 환수", cat:"rnd", amt:237000, y:2024, conf:"audit", src:"kaia",
 d:"연구비 용도외 사용 155건, 중복청구 23건, 세금계산서 취소 후 대금 미환입 89건 등 267건 적발, 23.7억 환수.", logic:["misuse","double","taxcxl"], risk:93},
{t:"참여연구원 인건비 유용 112건·55.6억 (최다 유형)", cat:"rnd", amt:556400, y:2024, conf:"audit", src:"kaia",
 d:"학생인건비 유용을 포함한 참여연구원 인건비 유용이 112건·55억6400만 원으로 최다.", logic:["payback","ghost"], risk:94},
{t:"물품 공급 없거나 부풀려 연구비 지급 20건·33.4억", cat:"rnd", amt:333700, y:2024, conf:"audit", src:"kaia",
 d:"실제 물품 공급이 없거나 단가를 부풀려 연구비를 지급한 20건, 33억3700만 원.", logic:["inflate","shell"], risk:94},
{t:"연구비 무단 인출 19건·18.6억", cat:"rnd", amt:185700, y:2024, conf:"audit", src:"kaia",
 d:"연구비를 무단으로 인출한 19건, 18억5700만 원 적발.", logic:["misuse"], risk:95},
{t:"국가연구비 105억 부정사용 적발", cat:"rnd", amt:1050000, y:2024, conf:"audit", src:"kaia",
 d:"국가연구비 105억 원 규모의 부정사용이 적발되어 환수·참여제한 조치.", logic:["misuse","payback"], risk:91},
{t:"국가 R&D 예산 유용·횡령 5년간 108억", cat:"rnd", amt:1080000, y:2024, conf:"agency", src:"press",
 d:"최근 5년간 국가 R&D 예산 유용·횡령 규모가 108억 원으로 집계.", logic:["misuse"], risk:88},
{t:"연구 미참여 직원에게 연구비 지급", cat:"rnd", amt:0, y:2024, conf:"stat", src:"kaia",
 d:"연구에 참여하지 않은 직원에게 연구비를 지급한 부당집행 유형.", logic:["ghost"], risk:92},
{t:"과제와 무관한 장비 구입", cat:"rnd", amt:0, y:2024, conf:"stat", src:"kaia",
 d:"수행 과제와 관련 없는 장비를 연구비로 구입한 용도외 사용.", logic:["misuse"], risk:88},
{t:"연구비 중복청구 23건", cat:"rnd", amt:0, y:2024, conf:"audit", src:"kaia",
 d:"동일 지출을 복수 과제에 중복 청구한 23건 적발.", logic:["double"], risk:91},
{t:"고의성 의심 6건 고발·수사의뢰", cat:"rnd", amt:0, y:2024, conf:"audit", src:"kaia",
 d:"연구비 횡령·유용 중 중요성이 크거나 고의성이 의심되는 6건을 고발·수사의뢰.", logic:["misuse","forge"], risk:96},

/* ── 농림·수산 ────────────────────────────────────────────────── */
{t:"실경작 없이 농업직불금 수급", cat:"nongsu", amt:0, y:2026, conf:"audit", src:"acrc",
 d:"실제 경작하지 않음에도 본인이 경작한 것처럼 신고해 농업직불금을 수급하는 대표 유형.", logic:["eligib","forge"], risk:93},
{t:"공공재정 부정수급 14.1만건·1296억 환수 (2025년)", cat:"nongsu", amt:12960000, y:2026, conf:"audit", src:"acrc",
 d:"311개 기관에서 확인된 부정수급 14만1781건, 환수 결정 1296억 원(전년 대비 24% 증가).", logic:["eligib","ghost"], risk:91},
{t:"제재부가금 500억 부과 (전년 대비 74% 급증)", cat:"nongsu", amt:5000000, y:2026, conf:"audit", src:"acrc",
 d:"공공재정환수법에 따른 제재부가금 부과액이 500억 원으로 74% 급증, 역대 최대 1796억 규모 제재.", logic:["eligib"], risk:88},
{t:"어선 허위 출·입항 실적 제출해 면세유 부정수급", cat:"nongsu", amt:0, y:2026, conf:"agency", src:"press",
 d:"어선의 허위 출·입항 실적을 제출해 어업용 면세유를 부정하게 수급.", logic:["forge","pad"], risk:92},
{t:"어업용 면세유를 차량·중장비에 사용", cat:"nongsu", amt:0, y:2026, conf:"agency", src:"press",
 d:"어업 목적으로 받은 면세유를 차량이나 중장비에 사용한 목적 외 사용.", logic:["misuse"], risk:91},
{t:"해상유 불법유통 8만4456㎘ — 67명 검거", cat:"nongsu", amt:0, y:2026, conf:"agency", src:"press",
 d:"해양경찰청 특별단속으로 67명 검거, 빼돌리거나 부정수급한 기름 8만4456㎘ 적발.", logic:["misuse","shell"], risk:95},
{t:"영암군, 4년간 386차례 138억 상당 석유 화물선 공급", cat:"nongsu", amt:1380000, y:2026, conf:"agency", src:"press",
 d:"전남 영암군에서 4년 가까이 386차례에 걸쳐 138억 원 상당 석유를 화물선에 몰래 공급하다 적발.", logic:["shell","misuse"], risk:96},
{t:"영흥 낚싯배 수상한 위판 — 면세유 편법수급 의혹", cat:"nongsu", amt:0, y:2026, conf:"agency", src:"press",
 d:"낚싯배가 위판 실적을 조작해 면세유를 편법 수급한 의혹 제기.", logic:["forge","pad"], risk:80},

/* ── 기타 공공재정 (에너지·교통·창업·장학) ──────────────────────── */
{t:"전력산업기반기금 비위 5824억·5359건 적발", cat:"gita", amt:58240000, y:2022, conf:"audit", src:"bai",
 d:"태양광 등 전력산업기반기금사업 점검에서 5824억 원(5359건)의 비위 사례 적발.", logic:["forge","inflate"], risk:92},
{t:"신재생에너지 금융지원 3010건·4898억 부당", cat:"gita", amt:48980000, y:2022, conf:"audit", src:"bai",
 d:"2019~2021년 신재생에너지 금융지원사업에서 3010건, 4898억 원의 부당 행위 적발.", logic:["forge","inflate"], risk:91},
{t:"가짜 세금계산서로 태양광 사업비 부풀려 과다 대출", cat:"gita", amt:0, y:2022, conf:"audit", src:"bai",
 d:"대출 시에는 부풀린 세금계산서를, 납세 시에는 정상 세금계산서를 사용하는 이중 장부 수법.", logic:["forge","inflate","taxcxl"], risk:96},
{t:"버섯재배사·곤충사육사로 위장한 허위 대출", cat:"gita", amt:0, y:2022, conf:"audit", src:"bai",
 d:"실경작 없이 농축산물 생산 시설로 위장해 신재생에너지 자금을 허위 대출.", logic:["eligib","shell","forge"], risk:94},
{t:"발전소 주변지역 지원금 1791건·574억 부당", cat:"gita", amt:5740000, y:2022, conf:"audit", src:"bai",
 d:"2017~2021년 25개 지자체 대상 점검에서 1791건, 574억 원의 부당 집행 적발.", logic:["misuse","inflate"], risk:89},
{t:"화물차주 23명 '카드깡'으로 유가보조금 1.3억 부정수급", cat:"gita", amt:13000, y:2020, conf:"agency", src:"molit",
 d:"주유업자와 결탁해 실제 주유하지 않거나 부풀린 금액을 카드 결제한 뒤 차액을 현금으로 환수.", logic:["rebate","forge"], risk:96},
{t:"지급대상 아닌 차량 주유 후 유가보조금 수령 928건", cat:"gita", amt:0, y:2021, conf:"audit", src:"molit",
 d:"유가보조금 지급대상이 아닌 다른 차량에 주유하고 보조금을 수령하거나 공모·가담한 928건.", logic:["eligib","misuse"], risk:91},
{t:"허위결제로 주유량 부풀려 과다 지급 15건", cat:"gita", amt:0, y:2021, conf:"audit", src:"molit",
 d:"허위결제로 주유량을 부풀려 유가보조금을 과다 지급받거나 공모한 15건.", logic:["inflate","forge"], risk:92},
{t:"탱크로리 이동차량 이용 주유 11건", cat:"gita", amt:0, y:2021, conf:"audit", src:"molit",
 d:"탱크로리 등 이동차량을 이용해 주유하고 보조금을 받거나 공모·가담한 11건.", logic:["forge","shell"], risk:90},
{t:"주유소에 카드 보관하고 결제 10건", cat:"gita", amt:0, y:2021, conf:"audit", src:"molit",
 d:"유류구매카드를 주유소에 보관시키고 결제하게 한 10건.", logic:["rebate","forge"], risk:89},
{t:"의심거래 주유소 300곳 점검 — 주유소 20곳·화물차 1015대 행정처분", cat:"gita", amt:0, y:2021, conf:"audit", src:"molit",
 d:"국토부·석유관리원 합동점검으로 주유소 20곳과 화물차 1015대에 행정처분 예정.", logic:["rebate","forge"], risk:88},
{t:"폐업 상태에서 유가보조금 수급", cat:"gita", amt:0, y:2026, conf:"audit", src:"acrc",
 d:"지원 대상이 아닌 차량에 주유하거나 폐업 상태에서 유가보조금을 계속 수급.", logic:["eligib","dead"], risk:93},
{t:"소공인 스마트제조 보조금 112개사 부정수급", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"112개사의 부정수급이 확인돼 환수·참여제한 절차 개시. 가격 부풀리기·페이백, 이면계약, 데이터 허위 전송.", logic:["inflate","payback","forge"], risk:94},
{t:"장비 가동 데이터 허위 전송 (폐업 사업장 포함)", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"장비·소프트웨어 가동 여부와 생산 데이터를 허위 전송, 이미 폐업한 사업장 장비가 정상 가동되는 것처럼 조작.", logic:["forge","pad","dead"], risk:95},
{t:"임차를 가장한 구매 이면계약", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"실제로는 구매하면서 임차한 것처럼 이면계약을 작성해 보조금 요건을 충족시킨 수법.", logic:["forge","shell"], risk:92},
{t:"소공인 지원사업 부정수급 7년새 33배 증가 (30억→980억)", cat:"gita", amt:9800000, y:2026, conf:"stat", src:"press",
 d:"2020년 30억 원 규모였던 부정수급이 2026년 980억 원으로 약 33배 증가.", logic:["inflate","payback"], risk:87},
{t:"배우자를 사업 참여자로 등록해 10개월간 인건비 지급 — 전액 환수", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"기업 대표가 배우자를 사업 참여자로 등록해 매달 인건비를 지급했으나 현장점검에서 근무 사실 입증 실패, 전액 환수.", logic:["family","ghost"], risk:95},
{t:"퇴사 직원 계속 근무 등록·허위 근태기록 제출", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"퇴사한 직원을 계속 근무하는 것처럼 등록하거나 허위 근태기록을 제출해 인건비 수령.", logic:["ghost","forge"], risk:94},
{t:"허위 세금계산서·결과보고서로 4327만원 편취 — 징역 8월", cat:"gita", amt:4328, y:2024, conf:"court", src:"court",
 d:"대표자가 허위 세금계산서와 결과보고서를 제출해 10회에 걸쳐 4327만9000원을 부정수급, 징역 8월 선고.", logic:["forge","inflate"], risk:98},
{t:"서류 위조로 정부지원금 14억 편취", cat:"gita", amt:140000, y:2024, conf:"court", src:"court",
 d:"서류를 위조해 정부 지원금 14억 원을 가로챈 사건.", logic:["forge","shell"], risk:97},
{t:"'창업지원금 깡' 불법 컨설팅 — 허위 세금계산서 발행", cat:"gita", amt:0, y:2026, conf:"agency", src:"press",
 d:"컨설팅업체가 지원금 현금화를 제안하며 허위 세금계산서를 발행하는 조직적 수법.", logic:["forge","rebate","shell"], risk:93},
{t:"허위 자발적 구매협약 동의서로 자격 없는 기업 지원 알선", cat:"gita", amt:0, y:2024, conf:"court", src:"court",
 d:"컨설팅업체와 의료기기 회사 구매팀장이 공모해 허위 동의서를 만들고 수수료를 챙긴 사건.", logic:["forge","rebate","eligib"], risk:95},
{t:"국가근로장학금 부정수급 6138건·2.5억 환수", cat:"gita", amt:24879, y:2020, conf:"agency", src:"kosaf",
 d:"2015~2020.8 부정수급 6138건 적발, 환수금액 2억4879만 원.", logic:["pad","forge"], risk:90},
{t:"근로장학금 허위근로 4161건 (전체의 68%)", cat:"gita", amt:0, y:2020, conf:"agency", src:"kosaf",
 d:"출근하지 않고 근무한 것처럼 꾸민 허위근로가 4161건으로 부정근로의 68%.", logic:["ghost","pad","forge"], risk:92},
{t:"근로장학금 대체근로 1829건·대리근로 148건", cat:"gita", amt:0, y:2020, conf:"agency", src:"kosaf",
 d:"다른 사람이 대신 근무하거나 대리 출근한 유형 각각 1829건, 148건.", logic:["pad","forge"], risk:88},
{t:"근로사실 없이 국가근로장학금 수령", cat:"gita", amt:0, y:2026, conf:"audit", src:"acrc",
 d:"권익위 점검에서 확인된 대표 유형. 실제 근로 사실 없이 국가근로장학금 수령.", logic:["ghost","pad"], risk:92},
{t:"예술단체, 단원들로부터 3000만원 페이백 — 수사 적발", cat:"gita", amt:3000, y:2025, conf:"agency", src:"mcst",
 d:"보조금 중 일부를 단원들로부터 3000만 원 돌려받아(페이백) 수사에 적발.", logic:["payback"], risk:96},
{t:"문체부 보조금 부정수급자 명단공표 사전통지 공시송달", cat:"gita", amt:0, y:2026, conf:"agency", src:"mcst",
 d:"공공재정환수법에 따른 고액부정청구자 명단공표 절차가 진행 중인 대상자에 대한 공시송달 공고.", logic:["forge"], risk:90},
{t:"제약회사 리베이트 신고 — 7억 과징금, 보상금 9600만원 지급", cat:"gita", amt:70000, y:2025, conf:"agency", src:"acrc",
 d:"신고로 7억 원의 과징금 부과·환수가 이뤄져 신고자에게 보상금 9600만 원 지급된 실제 보상 사례.", logic:["rebate"], risk:93},
];
